# Generated by Django 5.0.6 on 2024-09-27 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='user_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
